apiVersion: v1
kind: Pod
metadata:
  name: coit-backend1
  labels:
    apps: webserver
    soft: apache
  namespace: default
spec:
  containers:
    - image: coitlearning/coit-backend1:latest
      name: coit-backend1
      env: 
        - name: PYTHON_URL
          value: "http://coit-backend2"
        - name: MAVEN_REPO
          value: "https://repo.maven.apache.org"
      ports:
        - containerPort: 8080
          name: http-port
